### ISSUE TITLE
BottomSheetItem custom title color

### ISSUE THREAD

**Issue by cmakthat** [microsoft/fluentui-android#37] opened 2021-01-11 20:25 UTC
#### Describe the feature that you would like added

For BottomSheetItem, there is a way to customize the tint of the image icon but there is no way to change the color of the accompanied text. 

The equivalent on iOS, which is PopupMenuItem, has a property called "titleColor" which allows for a simple way to change the title color. 

Would it be possible to add this? Or is there already a way to do this?

Thanks for your time.

**Comment by joyeeta26** [comment] 2024-10-03 08:04
Hey @cmakthat, you can use v2 bottom sheet, it provides the ability to customise content as per needs.
Closing this issue, Please feel free to reopen if the issue is not resolved with v2 bottom sheet as well.
Thanks!
cc: @Dhoot

**Closed by joyeeta26** 2024-10-03 08:04 UTC
