### ISSUE TITLE
DrawerDialog.dismissDialog WindowManagerGlobal.findViewLocked IllegalArgumentException View not attached to window manager

### ISSUE THREAD

**Issue by vicalcazar** [microsoft/fluentui-android#185] opened 2022-05-12 16:44 UTC
Seeing several reports of this crash.  From this SO post, likely due to the activity being in a "finishing" state and the dialog no longer attached to the activity.  https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash

Below is a sample stacktrace:

```
android.view.WindowManagerGlobal.findViewLocked
WindowManagerGlobal.java, line 454
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView not attached to window manager

android.view.WindowManagerGlobal.findViewLocked WindowManagerGlobal.java:454
android.view.WindowManagerGlobal.removeView WindowManagerGlobal.java:380
android.view.WindowManagerImpl.removeViewImmediate WindowManagerImpl.java:140
android.app.Dialog.dismissDialog Dialog.java:701
android.app.Dialog.dismiss Dialog.java:684
androidx.appcompat.app.AppCompatDialog.dismiss SourceFile:140
com.microsoft.fluentui.drawer.DrawerDialog.dismissDialog SourceFile:213
com.microsoft.fluentui.drawer.DrawerDialog$sheetCallback$1.onStateChanged SourceFile:49
com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal SourceFile:1114
com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run SourceFile:1545
android.view.Choreographer$CallbackRecord.run Choreographer.java:911
android.view.Choreographer.doCallbacks Choreographer.java:686
android.view.Choreographer.doFrame Choreographer.java:619
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:897
android.os.Handler.handleCallback Handler.java:739
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:148
android.app.ActivityThread.main ActivityThread.java:7303
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1230
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1120
```

**Comment by phileo99** [comment] 2022-06-03 23:30
we have experienced this IllegalArgumentException crash as well during our testing

**Comment by joyeeta26** [comment] 2024-10-04 08:40
Hey @vicalcazar @phileo99 are you still facing this issue?

**Comment by joyeeta26** [comment] 2024-10-08 11:00
Closing this issue for now! Please feel free to reopen with fresh logs if the issue is still happening! Thanks!

**Closed by joyeeta26** 2024-10-08 11:00 UTC
Labels: question
