### ISSUE TITLE
Use version of TokenAutoComplete library that supports AndroidX

### ISSUE THREAD

**Issue by phileo99** [microsoft/fluentui-android#192] opened 2022-06-04 00:20 UTC
### Environment Information

- **Package version(s)**:  com.microsoft.fluentui:fluentui_others:0.0.20

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes)

Requested priority:  High

**Comment by JesseScott** [comment] 2022-12-22 21:27
Duplicate of #123

**Comment by joyeeta26** [comment] 2024-10-04 04:46
tokenautomcompleteversion was removed as part of PR #305. Hence closing this issue

**Closed by joyeeta26** 2024-10-04 04:46 UTC
